name: Python with playwrigth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright==0.3.0
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run the tests
      run: pytest --template=html1/index.html --report=report.html
      