name: Python with playwrigth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LOGIN_NAME: ${{ secrets.LOGIN_NAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-playwright==0.3.0
        pip install Faker
        pip install pytest-reporter-html1
        pip install python-dotenv
    - name: Run Pylint for tests 
      run: pylint tests/
    - name: Run Pylint for page objects
      run: pylint tests/
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run the tests
      run: pytest --template=html1/index.html --report=report.html
    - name: Upload Test Results
    - uses: actions/upload-artifact@v2
      with:
    - name: Test Results
      path: reports/report.html